spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/douban?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 2

  task:
    execution:
      pool:
        queue-capacity: 128 #等待队列的大小
        core-size: 5 #核心线程数
        max-size: 128 #最大线程数
        keep-alive: 60000  #线程空闲时间（当线程空闲60*1000 毫秒的时候会释放线程）
      thread-name-prefix: db-service-task-  #给线程起的名字前缀

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.craw.bean

#showSql
logging:
  level:
    com:
      example:
        mapper : debug



